### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Arata74** [TheCaduceus/CloneBot_V2#24]
cant deploy at okteto,already give config url

container 'clonebot' failed with exit code 1.

2022-07-24 08:26:01,348 - utils.config_loader - WARNING - Can't find General section in the Config File.
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebotTraceback (most recent call last):
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebot File "/usr/src/app/telegram_gcloner/telegram_gcloner.py", line 225, in <module>
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebot main()
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebot File "/usr/src/app/telegram_gcloner/telegram_gcloner.py", line 105, in main
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebot config.load_config()
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebot File "/usr/src/app/telegram_gcloner/utils/config_loader.py", line 40, in load_config
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebot input('Press enter to exit.')
2022-07-24 02:56:01.34 UTCclonebot-57ccbdb8d4-z5l62clonebotEOFError: EOF when reading a line
2022-07-24 02:56:01.48 UTCclonebot-57ccbdb8d4-z5l62clonebotPress enter to exit.

**Comment by TheCaduceus** [comment]
@Arata74 You modified the code and it triggered this Problem!

**Comment by Arata74** [comment]
2022-07-24 08:39:18,582 - utils.config_loader - WARNING - Can't find General section in the Config File.
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebotTraceback (most recent call last):
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebot File "/usr/src/app/telegram_gcloner/telegram_gcloner.py", line 225, in <module>
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebot main()
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebot File "/usr/src/app/telegram_gcloner/telegram_gcloner.py", line 105, in main
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebot config.load_config()
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebot File "/usr/src/app/telegram_gcloner/utils/config_loader.py", line 40, in load_config
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebot input('Press enter to exit.')
2022-07-24 03:09:18.58 UTCclonebot-58cdb6c57c-6dvmdclonebotEOFError: EOF when reading a line
2022-07-24 03:09:18.71 UTCclonebot-58cdb6c57c-6dvmdclonebotPress enter to exit.
2022-07-24 03:09:20.00 UTCclonebot-58cdb6c57c-6dvmd[pod-event]Successfully pulled image "ghcr.io/thecaduceus/clonebot_v2:main" in 416.584055ms
2022-07-24 03:09:27.00 UTCclonebot-58cdb6c57c-6dvmd[pod-event]Back-off restarting failed container
2022-07-24 03:09:40.00 UTCclonebot-58cdb6c57c-6dvmd[pod-event]Successfully pulled image "ghcr.io/thecaduceus/clonebot_v2:main" in 589.890833ms


same event refork again

**Comment by Arata74** [comment]
[General]
path_to_gclone = gclone

telegram_token = xxxxxxxxxxx
user_ids = xxxxxxxx
group_ids = -100xxxxxxxx

gclone_para_override = 

at github gits

**Comment by TheCaduceus** [comment]
@Arata74 That means the URL you providing as `CONFIG_FILE_URL` is invalid and bot unable to download `Config.ini` from it.

**Comment by Arata74** [comment]
![Screenshot_2022-07-24-12-09-32-737](https://user-images.githubusercontent.com/92328346/180631790-385f6cad-6c2b-4da6-9596-d6a1cb9cc798.png)

me also try use heroku also can't

**Comment by Arata74** [comment]
https://gist.github.com/Arata74/1551ed3010f2e8cf919fad26237fe92e/raw/config.ini

this link no problem at all
