### ISSUE TITLE
Bot starts but after gdrive link logging shows: gclone not found

### ISSUE THREAD

**Issue by zDuts** [TheCaduceus/CloneBot_V2#51]
Hi,
I can not get gclone to execute.
The bot starts I have path_to_gclone = gclone
and the gclone file located at /root/CloneBot_V2/telegram_gcloner/
Running ubuntu 20.04 (amd64 https://clonebot.tk/0:/v1.59.1%20(Dream)/Linux/Linux%20AMD%2064/)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/root/CloneBot_V2/telegram_gcloner/utils/fire_save_files.py", line 95, in run
    process = subprocess.Popen(command_line,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gclone'

Any ideas? 
Thanks in advance!

**Comment by zDuts** [comment]
Fixed it by changing path_to_gclone = gclone to path_to_gclone = ./gclone
Now it shows Unable to fetch Google Drive Link. for all links i try.

**Comment by TheCaduceus** [comment]
Just deploy using Docker and it will solve all your mistakes.
