### ISSUE TITLE
telegram.error.InvalidToken: Invalid token

### ISSUE THREAD

**Issue by idkimnoonesoignoreme** [TheCaduceus/CloneBot_V2#55]
Just deployed my app using this [Workflow](https://github.com/superfly/flyctl-actions) and I'm get this error `telegram.error.InvalidToken: Invalid token` I tried to revoke and generate new tokens but still it is same
**Here's the full log**

`2022-08-26T16:56:43.219 runner[dc68de42] sea [info] Starting instance

2022-08-26T16:56:43.876 runner[dc68de42] sea [info] Configuring virtual machine

2022-08-26T16:56:43.877 runner[dc68de42] sea [info] Pulling container image

2022-08-26T16:57:02.318 runner[dc68de42] sea [info] Unpacking image

2022-08-26T16:57:19.812 runner[dc68de42] sea [info] Preparing kernel init

2022-08-26T16:57:20.095 runner[dc68de42] sea [info] Configuring firecracker

2022-08-26T16:57:20.394 runner[dc68de42] sea [info] Starting virtual machine

2022-08-26T16:57:20.590 app[dc68de42] sea [info] Starting init (commit: f815f49)...

2022-08-26T16:57:20.620 app[dc68de42] sea [info] Preparing to run: `bash run.sh` as root

2022-08-26T16:57:20.643 app[dc68de42] sea [info] 2022/08/26 22:27:20 listening on [fdaa:0:89cd:a7b:bcab:dc68:de42:2]:22 (DNS: [fdaa::3]:53)

2022-08-26T16:57:21.563 app[dc68de42] sea [info] % Total % Received % Xferd Average Speed Time Time Time Current

2022-08-26T16:57:21.565 app[dc68de42] sea [info] Dload Upload Total Spent Left Speed

2022-08-26T16:57:22.008 app[dc68de42] sea [info] 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 162 100 162 0 0 128 0 0:00:01 0:00:01 --:--:-- 365

2022-08-26T16:57:25.836 app[dc68de42] sea [info] added 39 packages, and audited 40 packages in 3s

2022-08-26T16:57:25.836 app[dc68de42] sea [info] 9 packages are looking for funding

2022-08-26T16:57:25.837 app[dc68de42] sea [info] run `npm fund` for details

2022-08-26T16:57:25.838 app[dc68de42] sea [info] found 0 vulnerabilities

2022-08-26T16:57:26.198 app[dc68de42] sea [info] Starting up http-server, serving ./

2022-08-26T16:57:26.203 app[dc68de42] sea [info] http-server version: 14.1.1

2022-08-26T16:57:26.203 app[dc68de42] sea [info] http-server settings:

2022-08-26T16:57:26.203 app[dc68de42] sea [info] CORS: disabled

2022-08-26T16:57:26.203 app[dc68de42] sea [info] Cache: 3600 seconds

2022-08-26T16:57:26.203 app[dc68de42] sea [info] Connection Timeout: 120 seconds

2022-08-26T16:57:26.203 app[dc68de42] sea [info] Directory Listings: visible

2022-08-26T16:57:26.203 app[dc68de42] sea [info] AutoIndex: visible

2022-08-26T16:57:26.203 app[dc68de42] sea [info] Serve GZIP Files: false

2022-08-26T16:57:26.203 app[dc68de42] sea [info] Serve Brotli Files: false

2022-08-26T16:57:26.203 app[dc68de42] sea [info] Default File Extension: none

2022-08-26T16:57:26.203 app[dc68de42] sea [info] Available on:

2022-08-26T16:57:26.203 app[dc68de42] sea [info] http://127.0.0.1:8080

2022-08-26T16:57:26.203 app[dc68de42] sea [info] http://172.19.11.186:8080

2022-08-26T16:57:26.204 app[dc68de42] sea [info] http://172.19.11.187:8080

2022-08-26T16:57:26.204 app[dc68de42] sea [info] Hit CTRL-C to stop the server

2022-08-26T16:57:26.368 app[dc68de42] sea [info] 2022-08-26 22:27:26,368 - utils.config_loader - INFO - Found telegram_token: "5567598881:xxxxxxxxxoIThaU17DYXuHa7zAWTaY7z77Q"

2022-08-26T16:57:26.369 app[dc68de42] sea [info] 2022-08-26 22:27:26,368 - utils.config_loader - INFO - Found user_ids: 19950xxxxxx

2022-08-26T16:57:26.369 app[dc68de42] sea [info] 2022-08-26 22:27:26,368 - utils.config_loader - INFO - Found group_ids: -1

2022-08-26T16:57:26.369 app[dc68de42] sea [info] 2022-08-26 22:27:26,368 - utils.config_loader - INFO - Found path_to_gclone: gclone

2022-08-26T16:57:26.369 app[dc68de42] sea [info] 2022-08-26 22:27:26,369 - utils.config_loader - INFO - Found gclone_para_override:

2022-08-26T16:57:26.369 app[dc68de42] sea [info] 2022-08-26 22:27:26,369 - utils.config_loader - INFO - Found gclone: /usr/bin/gclone

2022-08-26T16:57:26.369 app[dc68de42] sea [info] 2022-08-26 22:27:26,369 - utils.config_loader - INFO - Found Bot Token: "5567598881:xxxxxxxxxxxIThaU17DYXuHa7zAWTaY7z77Q"

2022-08-26T16:57:26.370 app[dc68de42] sea [info] /usr/local/lib/python3.10/dist-packages/telegram/ext/messagequeue.py:230: TelegramDeprecationWarning: MessageQueue in its current form is deprecated and will be reinvented in a future release. See https://github.com/python-telegram-bot/python-telegram-bot/issues/2139 for a list of known bugs.

2022-08-26T16:57:26.370 app[dc68de42] sea [info] warnings.warn(

2022-08-26T16:57:26.370 app[dc68de42] sea [info] /usr/local/lib/python3.10/dist-packages/telegram/ext/messagequeue.py:94: TelegramDeprecationWarning: DelayQueue in its current form is deprecated and will be reinvented in a future release. See https://github.com/python-telegram-bot/python-telegram-bot/issues/2139 for a list of known bugs.

2022-08-26T16:57:26.370 app[dc68de42] sea [info] warnings.warn(

2022-08-26T16:57:26.371 app[dc68de42] sea [info] Traceback (most recent call last):

2022-08-26T16:57:26.371 app[dc68de42] sea [info] File "/usr/src/app/telegram_gcloner/telegram_gcloner.py", line 224, in <module>

2022-08-26T16:57:26.371 app[dc68de42] sea [info] main()

2022-08-26T16:57:26.371 app[dc68de42] sea [info] File "/usr/src/app/telegram_gcloner/telegram_gcloner.py", line 114, in main

2022-08-26T16:57:26.371 app[dc68de42] sea [info] my_bot = MQBot(config.TELEGRAM_TOKEN, request=request, mqueue=q)

2022-08-26T16:57:26.371 app[dc68de42] sea [info] File "/usr/src/app/telegram_gcloner/telegram_gcloner.py", line 36, in __init__

2022-08-26T16:57:26.371 app[dc68de42] sea [info] super(MQBot, self).__init__(*args, **kwargs)

2022-08-26T16:57:26.371 app[dc68de42] sea [info] File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 194, in __init__

2022-08-26T16:57:26.372 app[dc68de42] sea [info] self.token = self._validate_token(token)

2022-08-26T16:57:26.372 app[dc68de42] sea [info] File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 358, in _validate_token

2022-08-26T16:57:26.372 app[dc68de42] sea [info] raise InvalidToken()

2022-08-26T16:57:26.372 app[dc68de42] sea [info] telegram.error.InvalidToken: Invalid token

2022-08-26T16:57:53.805 runner[468061ee] sea [info] Shutting down virtual machine

2022-08-26T16:57:53.906 app[468061ee] sea [info] Sending signal SIGINT to main child process w/ PID 515`

**Here's how my config.ini looks like **
![2022_08_26_23_04_33~2](https://user-images.githubusercontent.com/111246766/186962935-9ffc382e-2bfb-47c8-8e22-1a24e8855bac.jpg)

**Comment by TheCaduceus** [comment]
@idkimnoonesoignoreme Telegram bot API token should not be between `""`
