### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by theseeker99** [TheCaduceus/CloneBot_V2#75]
The bot is started correctly. but it can't clone.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/CloneBot_V2/telegram_gcloner/utils/fire_save_files.py", line 95, in run
    process = subprocess.Popen(command_line,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './telegram_gcloner/gclone'

**Comment by sridhar885** [comment]
for me also same error did you solved it

**Comment by TheCaduceus** [comment]
Use `chmod -x {path}` before running the bot.

**Comment by theseeker99** [comment]
> 

Still not fixed 😓

**Comment by theseeker99** [comment]
> Use `chmod -x {path}` before running the bot.

Still not fixed 😓

**Comment by theseeker99** [comment]
> for me also same error did you solved it

Nope
