### ISSUE TITLE
issue on windows while cloning 

### ISSUE THREAD

**Issue by RealNoobieDrive** [TheCaduceus/CloneBot_V2#78]
getting this error while cloning 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\demo\Downloads\Compressed\CloneBot_V2-2.2.9\CloneBot_V2-2.2.9\telegram_gcloner\utils\fire_save_files.py", line 95, in run
    process = subprocess.Popen(command_line,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by TheCaduceus** [comment]
@RealNoobieDrive You have not downloaded the correct gclone file as per your system.

**Comment by RealNoobieDrive** [comment]
where to find gclone for windows ??
